#!/home/mbrainz/perl/bin/perl -w
# vi: set ts=4 sw=4 :

use strict;

use AnanovaXMLTV;

my $region = shift;

my @c = AnanovaXMLTV->channels($region);
print "$_->[0]\t$_->[1]\n" for @c;

# eof showchannels
